# PROJECT SETTINGS
#-----------------------------------------------------------

project_settings:
  # Number of costumers connected
  connections: 100
  # Project lifetime [years]
  project_lifetime: 20
  # Operation Time Steps [hours]
  operation_time_steps: 21
  # Time Step Duration [hours]
  time_step_duration: 1
  # Discount rate
  nominal_discount_rate: 0.1

  # Capex model: "upfront" (lump sum cost at year 0) or "annuity" (annual distributed cost, discounted to year 0)
  capex_model: "upfront"  
  # Maximum Capex per connection [USD/connection]
  max_capex: 1000 

  # Weighted Average Cost of Capital (WACC)
  wacc_calculation: true
  wacc:
    cost_of_equity: 0.12
    cost_of_debt: 0.11
    equity_share: 0.1
    debt_share: 0.9
    tax_rate: 0.02

  # Project Subsidies/Grants
  subsidies:
    capital_cost_subsidies: 0.3    # Capital cost subsidies as a percentage of total capital cost [-]
    subsidies_per_connection: 0  # Subsidies per connection [USD/connection]

# PROBABILISTIC CONSTRAINTS
#--------------------------------------------------------------

uncertainty:
# Number of simulations in errors data
  n_simulations: 100         
  # Average duration of daily outages [hours]              
  outage_duration: 3
  # Probability of a daily outage (0 for no outages)
  outage_probability: 0.9
  # Probability parameter of successful islanding
  islanding_probability: 0.9
 
# TECHNO-ECONOMIC PARAMETERS
#--------------------------------------------------------------

# Solar PV Parameters
solar:
  capex: 758                  # Specific investment cost in USD/kW
  opex: 0                     # O&M cost in USD/kWh
  lifetime: 20                # Lifetime of solar PV system in years

# Battery Parameters
battery:
  capex: 400.0                # Specific investment cost in USD/kWh
  opex: 0.01                  # O&M cost in USD/kWh (cycle cost)
  lifetime: 10                # Expected lifetime of battery system in years
  operation:
    charge_time: 5            # Battery charging time in hours
    discharge_time: 5         # Battery discharging time in hours
  efficiency:
    charge: 0.95              # Battery charging efficiency
    discharge: 0.95           # Battery discharging efficiency
  SOC:
    min: 0.2                  # Minimum state of charge as a percentage
    max: 0.9                  # Maximum state of charge as a percentage
    initial: 0.5              # Initial state of charge as a percentage

# Diesel Generator Parameters
generator:
  capex: 350.0                # Specific investment cost in USD/kW
  fuel_cost: 0.2              # Cost of diesel generation per kWh
  lifetime: 20                # Lifetime of diesel generator in years

# Grid Parameters
grid:
  day_ahead_price: 0.55                   # Price for day-ahead grid export [USD/kWh]
  grid_exchange_cost: 0.3                 # Costs for importing unsatisfied energy from the grid (instantaneous grid exchange) [USD/kWh]

# Retail Electricity Tariff
retail_tariff:
  elec_price: 0.2              # Electricity price in USD/kWh

# SOLVER SETTINGS
#--------------------------------------------------------------

solver_settings:
  # Ipopt solver settings
  ipopt_options:
    linear_solver: ma27
    max_iter: 100000
    tol: 1e-6
  # Gurobi solver settings
  gurobi_options:
    time_limit: 60
    mipgap: 0.01
  # GLPK solver settings
  glpk_options:
    presolve: true    # Use presolve to simplify the problem (true/false)
    msg_lev: 3        # Message level (0-4)
    tm_lim: 100000    # Time limit in milliseconds for solving the problem